version: '3.1'

services:

  nginx:
    image: faisaladlin/nginx:1.14-fastcgi-php
    environment:
      SERVER_NAME: ${SERVER_NAME}
      PHP_HOST: ${PHP_HOST}
      TIMEOUT: ${TIMEOUT}
      TZ: ${TZ}
    ports:
      - ${WEB_PORT_MAP}:80
    volumes:
      - ./:/var/www
    links:
      - php

  php:
    image: faisaladlin/php:7.2-fpm-laravel
    environment:
      XDEBUG: ${XDEBUG}
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      TZ: ${TZ}
    volumes:
      - ./:/var/www
    links:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${DB_PORT_MAP}:3306
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
